name: Build & publish GulogGratis XML

on:
  schedule:
    # 12:00 Europe/Copenhagen ≈ 10:00 UTC (sommer) og 11:00 UTC (vinter)
    - cron: '0 10 * * *'
    - cron: '0 11 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

env:
  TZ: Europe/Copenhagen
  CSV_PATH: cms.csv
  CATEGORY_PATH: /camping/campingvogn
  BASE_URL: https://viborg-caravancenter.dk/campingvogne

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Kør kun ved lokal 12:00 eller når du manuelt trigger workflowet
      - id: gate
        name: Gate on local time 12:00 Europe/Copenhagen
        run: |
          python - <<'PY'
          from datetime import datetime
          from zoneinfo import ZoneInfo
          now = datetime.now(ZoneInfo("Europe/Copenhagen"))
          run_now = (now.hour == 12) or ("workflow_dispatch" in "${{ github.event_name }}")
          with open("${{ github.output }}".upper(), "a") as f:
              f.write(f"run_now={'true' if run_now else 'false'}\n")
          print("Local time:", now.isoformat(), "run_now:", run_now)
          PY

      - if: steps.gate.outputs.run_now == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - if: steps.gate.outputs.run_now == 'true'
        name: Install deps
        run: pip install -r requirements.txt

      - if: steps.gate.outputs.run_now == 'true'
        name: Generate XML
        run: python feed.py

      - if: steps.gate.outputs.run_now == 'true'
        name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - if: steps.gate.outputs.run_now == 'true'
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      # E-mail ved fejl (Office 365/SMTP)
      - name: Send failure email (SMTP)
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "[GG FEED] Build FAILED: ${{ github.repository }}"
          from: ${{ secrets.MAIL_FROM }}
          to: ${{ secrets.MAIL_TO }}
          content_type: text/plain
          body: |
            Repo: ${{ github.repository }}
            Run:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
